export const articles = [
    {
        id: 1,
        title: "۱۰ ترند بازاریابی دیجیتال در ۲۰۲۵",
        description: "جدیدترین روندهای بازاریابی دیجیتال که برندها باید در سال ۲۰۲۵ جدی بگیرند.",
        thumbnail: "/assets/images/post-cover-1.webp",
        createdAt: "2025-09-01",
        readTime: "6 دقیقه",
    },
    {
        id: 2,
        title: "چطور نرخ تبدیل سایت رو دو برابر کنیم؟",
        description: "راهکارهای عملی برای بهبود تجربه کاربری و افزایش نرخ تبدیل در صفحات فرود.",
        thumbnail: "/assets/images/post-cover-2.webp",
        createdAt: "2025-08-27",
        readTime: "5 دقیقه",
    },
    {
        id: 3,
        title: "راهنمای کامل تبلیغات گوگل ادز",
        description: "نکات کلیدی برای طراحی کمپین‌های بهینه و کاهش هزینه‌های تبلیغات در گوگل.",
        thumbnail: "/assets/images/post-cover-3.webp",
        createdAt: "2025-08-20",
        readTime: "7 دقیقه",
    },
    {
        id: 4,
        title: "راز موفقیت برندهای بزرگ در شبکه‌های اجتماعی",
        description: "تحلیل استراتژی برندهای موفق و چگونگی الهام گرفتن از آن‌ها در مارکتینگ.",
        thumbnail: "/assets/images/post-cover-4.webp",
        createdAt: "2025-08-15",
        readTime: "4 دقیقه",
    },
    {
        id: 5,
        title: "۵ اشتباه رایج در استراتژی محتوایی",
        description: "اشتباهاتی که کسب‌وکارها در بازاریابی محتوایی مرتکب می‌شوند و راه‌حل آن‌ها.",
        thumbnail: "/assets/images/post-cover-1.webp",
        createdAt: "2025-08-10",
        readTime: "5 دقیقه",
    },
    {
        id: 6,
        title: "بهترین ابزارهای آنالیز سئو در سال جدید",
        description: "معرفی و مقایسه ابزارهای پرکاربرد برای بررسی رتبه، بک‌لینک و بهینه‌سازی سایت.",
        thumbnail: "/assets/images/post-cover-2.webp",
        createdAt: "2025-08-05",
        readTime: "6 دقیقه",
    },
    {
        id: 7,
        title: "چگونه با ایمیل مارکتینگ فروش را افزایش دهیم؟",
        description: "استراتژی‌ها و نمونه‌های موفق از ایمیل مارکتینگ برای افزایش نرخ فروش.",
        thumbnail: "/assets/images/post-cover-3.webp",
        createdAt: "2025-08-01",
        readTime: "5 دقیقه",
    },
    {
        id: 8,
        title: "تکنیک‌های بهینه‌سازی نرخ کلیک (CTR)",
        description: "روش‌هایی برای طراحی بهتر عنوان، توضیحات و CTA جهت افزایش CTR.",
        thumbnail: "/assets/images/post-cover-4.webp",
        createdAt: "2025-07-28",
        readTime: "4 دقیقه",
    },
    {
        id: 9,
        title: "اهمیت پرسونای مشتری در بازاریابی",
        description: "چرا شناخت دقیق مخاطب هدف در موفقیت کمپین‌های بازاریابی حیاتی است.",
        thumbnail: "/assets/images/post-cover-1.webp",
        createdAt: "2025-07-25",
        readTime: "5 دقیقه",
    },
    {
        id: 10,
        title: "مارکتینگ اتوماسیون؛ صرفه‌جویی در زمان و هزینه",
        description: "آشنایی با ابزارهای اتوماسیون مارکتینگ و مزایای استفاده از آن‌ها برای کسب‌وکارها.",
        thumbnail: "/assets/images/post-cover-2.webp",
        createdAt: "2025-07-20",
        readTime: "6 دقیقه",
    },
];
